tabRounding = 4.0
scrollbarRounding = 9.0
windowRounding = 7.0
grabRounding = 3.0
frameRounding = 3.0
popupRounding = 4.0
childRounding = 4.0

[colors]
WindowBg           = [26, 26, 33, 255]
MenuBarBg          = [41, 41, 54, 255]
Border             = [112, 94, 156, 74]
BorderShadow       = [0, 0, 0, 61]
Text               = [255, 255, 255, 255]
TextDisabled       = [128, 128, 128, 255]
Header             = [33, 33, 43, 255]
HeaderHovered      = [48, 51, 64, 255]
HeaderActive       = [41, 41, 54, 255]
Button             = [33, 33, 43, 255]
ButtonHovered      = [48, 51, 64, 255]
ButtonActive       = [41, 41, 54, 255]
CheckMark          = [189, 148, 250, 255]
PopupBg            = [26, 26, 33, 235]
SliderGrab         = [112, 94, 156, 138]
SliderGrabActive   = [189, 148, 250, 138]
FrameBg            = [33, 33, 43, 255]
FrameBgHovered     = [48, 51, 64, 255]
FrameBgActive      = [41, 41, 54, 255]
Tab                = [41, 41, 54, 255]
TabHovered         = [61, 61, 82, 255]
TabActive          = [51, 56, 69, 255]
TabUnfocused       = [41, 41, 54, 255]
TabUnfocusedActive = [41, 41, 54, 255]
TitleBg            = [41, 41, 54, 255]
TitleBgActive      = [41, 41, 54, 255]
TitleBgCollapsed   = [41, 41, 54, 255]
ScrollbarBg        = [26, 26, 33, 255]
ScrollbarGrab      = [41, 41, 54, 255]
ScrollbarGrabHovered = [48, 51, 64, 255]
ScrollbarGrabActive  = [61, 61, 82, 255]
Separator          = [112, 94, 156, 255]
SeparatorHovered   = [189, 148, 250, 255]
SeparatorActive    = [214, 148, 255, 255]
ResizeGrip         = [112, 94, 156, 74]
ResizeGripHovered  = [189, 148, 250, 74]
ResizeGripActive   = [214, 148, 255, 74]
DockingPreview     = [112, 94, 156, 255]
